version: '3'
services:
  meuprimeirocrudgo:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DATABASE_NAME=crudInit
      - DATABASE_COLLECTION=users
      - JWT_SECRET_KEY=WORVNROWNI*&(¨%kBVKJKJK*&(%¨&rLKJKBKJB&¨$¨%&%&JBKJKB))
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - meuprimeirocrudgo_network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - meuprimeirocrudgo_network


networks:
  meuprimeirocrudgo_network:
